package com.ruleengine.Rule.Engine.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "rules") // Specify your MongoDB collection name
public class Rule {
    @Id
    private String id; // This will be automatically generated by MongoDB
    private String ruleString; // The original rule string
    private Node ast; // The corresponding Abstract Syntax Tree

    public Rule(String ruleString, Node ast) {
        this.ruleString = ruleString;
        this.ast = ast;
    }

    // Getters and Setters
    public String getRuleString() {
        return ruleString;
    }

    public void setRuleString(String ruleString) {
        this.ruleString = ruleString;
    }

    public Node getAst() {
        return ast;
    }

    public void setAst(Node ast) {
        this.ast = ast;
    }
}
